---
# tasks file for web_nginx

- name: Install nginx
  dnf:
    name: nginx
    state: latest

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy nginx config file
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

- name: Clone git repository with site
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.root }}"
    force: yes
  with_items: "{{ webserver_content }}"

- name: Copy sites config file
  template:
    src: etc/nginx/conf.d/webproxima.ru.conf.j2
    dest: /etc/nginx/conf.d/webproxima.ru.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx


