---
# tasks file for web_nginx

- name: Install nginx
  dnf:
    name: nginx
    state: latest

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Clone git repository with site
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.root }}"
    force: yes
  with_items: "{{ webserver_content }}"


