---
# tasks file for common

- name: Install epel-repo
  dnf:
    name: epel-release
    state: latest

- name: Enable 80 port
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled

